### ISSUE TITLE
Error running wnfs-migration

### ISSUE THREAD

**Issue by jeffgca** [fission-suite/wnfs-migration#13]
On the final step fo rupdating the data root when running wnfs-migration on my `jeffg` account, I get this error looping for a while.

```
Error while setting data root:
Error: Failed to update data root. HTTP Code 401. Message: Expired
    at setDataRoot (file:///Users/jeff/code/node/globals/node_modules/wnfs-migration/lib/cli/index.js:149:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Module.run (file:///Users/jeff/code/node/globals/node_modules/wnfs-migration/lib/cli/index.js:56:17)
    at async file:///Users/jeff/code/node/globals/node_modules/wnfs-migration/lib/index.js:4:5
```

**Comment by jeffgca** [comment]
Some notes on this:

1. this is as far as I've gotten migrating my old fs to the latest, and it's great it is producing errors!
2. I'll open another, more specific issue for guarding against infinite error loops in the migration

**Comment by icidasset** [comment]
I'll take a closer look at this. Since the issue is that the UCAN was expired when it got to the server, it might just be that we need to create the UCAN when doing the actual request, not before.

@therealjeffg Do you happen to remember if it retried the data root update? Or to put it differently, did you get multiple errors?

**Comment by matheus23** [comment]
This is a long shot, but is your system clock out of sync perhaps @therealjeffg?
